apiVersion: v1
kind: Service
metadata:
  name: nginx-external
spec:
  type: NodePort
  selector:
    app: multitool-nginx
  ports:
    - name: nginx-external-port
      protocol: TCP
      port: 80       # Порт внутри сервиса
      targetPort: 80 # Порт внутри контейнера nginx
      nodePort: 30080 # Внешний порт (диапазон 30000-32767)