---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/k8s-data # Папка на ноде
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-storage
  template:
    metadata:
      labels:
        app: shared-storage
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo "$(date): Writing to PVC" >> /mnt/data.txt; sleep 5; done']
        volumeMounts:
        - name: storage
          mountPath: /mnt
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: storage
          mountPath: /mnt
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: local-pvc
