{
 "title": "Node System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Место на файловой системе",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Утилизация CPU ",
   "type": "gauge",
   "description": "(в процентах, 100 − idle)",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободная оперативная память",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "stat",
   "description": "CPU Load Average (1/5/15 min)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1",
     "legendFormat": "{{job}} {{instance}} load{{__name__}}"
    },
    {
     "expr": "node_load5",
     "legendFormat": "{{job}} {{instance}} load{{__name__}}"
    },
    {
     "expr": "node_load15",
     "legendFormat": "{{job}} {{instance}} load{{__name__}}"
    }
   ]
  }
 ]
}